excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cxicai.github.io
name: colours of the wind
description: +60 | 01's
author: cxicai
avatar: <a href="http://s40.photobucket.com/user/chaexx/media/Mobile%20Uploads/image_zpsfduqsvhk.jpg.html" target="_blank"><img src="http://i40.photobucket.com/albums/e207/chaexx/Mobile%20Uploads/image_zpsfduqsvhk.jpg" border="0" alt=" photo image_zpsfduqsvhk.jpg"/></a>
ga_domain: 
ga_tracking_id: 